// Time-zone names that calendar services accept.
// Browsers sometimes report legacy IANA ids (e.g. "America/Indianapolis"); Outlook prefers Windows zone names.

const LEGACY = {
  'America/Indianapolis': 'America/Indiana/Indianapolis',
  'America/Fort_Wayne': 'America/Indiana/Indianapolis',
  'America/Louisville': 'America/Kentucky/Louisville',
  'America/Buenos_Aires': 'America/Argentina/Buenos_Aires',
  'Asia/Calcutta': 'Asia/Kolkata',
  'Asia/Saigon': 'Asia/Ho_Chi_Minh',
  'Asia/Katmandu': 'Asia/Kathmandu',
  'Asia/Rangoon': 'Asia/Yangon',
  'Europe/Kiev': 'Europe/Kyiv',
  'Atlantic/Faeroe': 'Atlantic/Faroe',
  'US/Eastern': 'America/New_York',
  'US/Central': 'America/Chicago',
  'US/Mountain': 'America/Denver',
  'US/Pacific': 'America/Los_Angeles',
  'US/East-Indiana': 'America/Indiana/Indianapolis',
  'Etc/UTC': 'UTC',
  'Etc/GMT': 'UTC',
};

// CLDR windowsZones (territory "001"/common entries).
const WINDOWS = {
  'Pacific/Honolulu': 'Hawaiian Standard Time',
  'America/Anchorage': 'Alaskan Standard Time',
  'America/Los_Angeles': 'Pacific Standard Time',
  'America/Vancouver': 'Pacific Standard Time',
  'America/Tijuana': 'Pacific Standard Time (Mexico)',
  'America/Phoenix': 'US Mountain Standard Time',
  'America/Denver': 'Mountain Standard Time',
  'America/Edmonton': 'Mountain Standard Time',
  'America/Boise': 'Mountain Standard Time',
  'America/Chicago': 'Central Standard Time',
  'America/Winnipeg': 'Central Standard Time',
  'America/Indiana/Knox': 'Central Standard Time',
  'America/Menominee': 'Central Standard Time',
  'America/Regina': 'Canada Central Standard Time',
  'America/Mexico_City': 'Central Standard Time (Mexico)',
  'America/New_York': 'Eastern Standard Time',
  'America/Toronto': 'Eastern Standard Time',
  'America/Detroit': 'Eastern Standard Time',
  'America/Kentucky/Louisville': 'Eastern Standard Time',
  'America/Indiana/Indianapolis': 'US Eastern Standard Time',
  'America/Indiana/Marengo': 'US Eastern Standard Time',
  'America/Indiana/Vevay': 'US Eastern Standard Time',
  'America/Halifax': 'Atlantic Standard Time',
  'America/Puerto_Rico': 'SA Western Standard Time',
  'America/St_Johns': 'Newfoundland Standard Time',
  'America/Bogota': 'SA Pacific Standard Time',
  'America/Lima': 'SA Pacific Standard Time',
  'America/Sao_Paulo': 'E. South America Standard Time',
  'America/Argentina/Buenos_Aires': 'Argentina Standard Time',
  'Atlantic/Reykjavik': 'Greenwich Standard Time',
  'Europe/London': 'GMT Standard Time',
  'Europe/Dublin': 'GMT Standard Time',
  'Europe/Lisbon': 'GMT Standard Time',
  'Europe/Berlin': 'W. Europe Standard Time',
  'Europe/Amsterdam': 'W. Europe Standard Time',
  'Europe/Rome': 'W. Europe Standard Time',
  'Europe/Stockholm': 'W. Europe Standard Time',
  'Europe/Vienna': 'W. Europe Standard Time',
  'Europe/Zurich': 'W. Europe Standard Time',
  'Europe/Oslo': 'W. Europe Standard Time',
  'Europe/Paris': 'Romance Standard Time',
  'Europe/Brussels': 'Romance Standard Time',
  'Europe/Madrid': 'Romance Standard Time',
  'Europe/Copenhagen': 'Romance Standard Time',
  'Europe/Warsaw': 'Central European Standard Time',
  'Europe/Zagreb': 'Central European Standard Time',
  'Europe/Budapest': 'Central Europe Standard Time',
  'Europe/Prague': 'Central Europe Standard Time',
  'Europe/Belgrade': 'Central Europe Standard Time',
  'Europe/Athens': 'GTB Standard Time',
  'Europe/Bucharest': 'GTB Standard Time',
  'Europe/Helsinki': 'FLE Standard Time',
  'Europe/Kyiv': 'FLE Standard Time',
  'Europe/Riga': 'FLE Standard Time',
  'Europe/Sofia': 'FLE Standard Time',
  'Europe/Tallinn': 'FLE Standard Time',
  'Europe/Vilnius': 'FLE Standard Time',
  'Europe/Istanbul': 'Turkey Standard Time',
  'Europe/Moscow': 'Russian Standard Time',
  'Africa/Cairo': 'Egypt Standard Time',
  'Africa/Johannesburg': 'South Africa Standard Time',
  'Africa/Lagos': 'W. Central Africa Standard Time',
  'Africa/Nairobi': 'E. Africa Standard Time',
  'Asia/Jerusalem': 'Israel Standard Time',
  'Asia/Riyadh': 'Arab Standard Time',
  'Asia/Dubai': 'Arabian Standard Time',
  'Asia/Kolkata': 'India Standard Time',
  'Asia/Shanghai': 'China Standard Time',
  'Asia/Hong_Kong': 'China Standard Time',
  'Asia/Singapore': 'Singapore Standard Time',
  'Asia/Tokyo': 'Tokyo Standard Time',
  'Asia/Seoul': 'Korea Standard Time',
  'Australia/Sydney': 'AUS Eastern Standard Time',
  'Australia/Melbourne': 'AUS Eastern Standard Time',
  'Australia/Brisbane': 'E. Australia Standard Time',
  'Australia/Perth': 'W. Australia Standard Time',
  'Pacific/Auckland': 'New Zealand Standard Time',
  UTC: 'UTC',
};

export function ianaZone(tz) {
  return LEGACY[tz] || tz || 'UTC';
}

// Windows zone name for Outlook, or null when unknown.
export function windowsZone(tz) {
  return WINDOWS[ianaZone(tz)] || null;
}
